[versions]
ktor = "3.0.1"
koin = "4.0.0"
navigation3-ui = "1.0.1"
datastore = "1.1.1"

[libraries]
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3-ui" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
